export const boxData = [
    { value: 'people', label: 'people' },
    { value: 'cars-vehicles', label: 'cars-vehicles' },
    { value: 'Nature-plants', label: 'Nature-plants' },
    { value: 'animals-pets', label: 'Animals-pets' },
    { value: 'architecture', label: 'Architecture' },
    { value: 'food-drink' , label: 'Food & Drink' },
    { value:  'science-technology', label: 'Science & Technology' },
    { value:  'places-travel', label: 'Places & Travel' },
    { value: 'furniture-home', label: 'Furniture & Home' },
    { value: 'electronics-gadgets', label: 'Electronics & Gadgets' },
    { value: 'Art-abstract', label: 'Art & Abstract' },
    { value: 'Characters-creatures', label: 'Characters & Creatures' },
    { value: 'Cultural-heritage-history', label: 'Cultural Heritage & History' },
    { value: 'Fashion-style', label: 'Fashion & Style' },
    { value: 'Music', label: 'Music' },
    { value: 'News-politics', label: 'News & Politics' },
    { value: 'Sports-fitness', label: 'Sports & Fitness' },
    { value: 'Weapons-military', label: 'Weapons & Military' },
    { value: 'Art-abstract', label: 'Art & Abstract' },
    { value: 'Characters-creatures', label: 'Characters & Creatures' },
    { value: 'Cultural-heritage-history', label: 'Cultural Heritage & History' },
    { value: 'Fashion-style', label: 'Fashion & Style' },
    { value: 'Music', label: 'Music' },
    { value: 'News-politics', label: 'News & Politics' },
    { value: 'Sports-fitness', label: 'Sports & Fitness' },
    { value: 'Weapons-military', label: 'Weapons & Military' }
];