import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    contener:{
        width:"100%",
        height:150,
        padding:30,
        justifyContent:'center',
        position:'relative',
        borderStyle:"solid",
        borderWidth:1,
        borderColor:"#b6b6b638",
        borderLeftColor:'transparent',
        borderRightColor:"transparent"
    },
    dateBox:{
        borderRadius:500,  
        width:110,
        height:110,
        borderStyle:"solid",
        borderWidth:2,
        alignItems:'center',
        justifyContent:'center',
        borderColor:"#c6d8cd",
        backgroundColor:"#c6d8cd81",
        color:"#c6d8cd",
    },
    dateBoxSAr:{
        borderRadius:500,  
        width:110,
        height:110,
        borderStyle:"solid",
        borderWidth:2,
        alignItems:'center',
        justifyContent:'center',
        borderColor:"#c6d8cd",
        backgroundColor:"#c6d8cd81",
        color:"#c6d8cd",
        left:"70%"
    },
    dateBoxPur:{
        borderRadius:500,  
        width:110,
        height:110,
        borderStyle:"solid",
        borderWidth:2,
        alignItems:'center',
        justifyContent:'center',
        borderColor:"#9697C8",
        backgroundColor:"#d2d6e6",
        color:"#9697C8"
    },
    dateBoxPurAr:{
        borderRadius:500,  
        width:110,
        height:110,
        borderStyle:"solid",
        borderWidth:2,
        alignItems:'center',
        justifyContent:'center',
        borderColor:"#9697C8",
        backgroundColor:"#d2d6e6",
        color:"#9697C8",
        left:"70%"
    },
    dateBoxRed:{
        borderRadius:500,  
        width:110,
        height:110,
        borderStyle:"solid",
        borderWidth:2,
        alignItems:'center',
        justifyContent:'center',
        borderColor:"#F3BCBB",
        backgroundColor:"#EED2D4",
        color:"#F3BCBB",
    },
    dateBoxRedAr:{
        borderRadius:500,  
        width:110,
        height:110,
        borderStyle:"solid",
        borderWidth:2,
        alignItems:'center',
        justifyContent:'center',
        borderColor:"#F3BCBB",
        backgroundColor:"#EED2D4",
        color:"#F3BCBB",
        left:"70%"
    },
    name:{
        fontSize:18,
        position:"absolute",
        left:"50%",
        top:'70%'
    },
    nameAr:{
        fontSize:18,
        position:"absolute",
        left:"38%",
        top:'70%'
    },
    time:{
        fontSize:18,
        position:"absolute",
        left:"50%",
        top:'20%',
        fontWeight:"bold",

    },
    timeAr:{
        fontSize:18,
        position:"absolute",
        left:"40%",
        top:'20%',
        fontWeight:"400",

    },
    phone:{
        fontSize:15,
        position:"absolute",
        left:"50%",
        top:'120%',
        color:'#C3C5F3',
    },
    phoneAr:{
        fontSize:15,
        position:"absolute",
        left:"53%",
        top:'120%',
        color:'#C3C5F3',
    },
    deleteAr:{
        position:'absolute' ,
        top:"70%", 
        left:"10%",
    },
    delete:{
        position:'absolute' ,
        top:"70%", 
        left:"95%",
    },
})